ALTER TABLE APP_AGEND_UT."USER" ADD CONSTRAINT USER_IDENTIFICATION_TYPE_ID_FK
FOREIGN KEY (IDENTIFICATION_TYPE_ID)
REFERENCES APP_AGEND_UT.IDENTIFICATION_TYPE (IDENTIFICATION_TYPE_ID);

ALTER TABLE APP_AGEND_UT."USER" ADD CONSTRAINT USER_ROLE_ID_FK
FOREIGN KEY (ROLE_ID)
REFERENCES APP_AGEND_UT."ROLE" (ROLE_ID);

ALTER TABLE APP_AGEND_UT.WORK_SHIFT ADD CONSTRAINT WORK_SHIFT_SCHEDULE_ID_FK
FOREIGN KEY (SCHEDULE_ID)
REFERENCES APP_AGEND_UT.SCHEDULE (SCHEDULE_ID);

ALTER TABLE APP_AGEND_UT.WORK_SHIFT ADD CONSTRAINT WORK_SHIFT_USER_ID_FK
FOREIGN KEY (USER_ID)
REFERENCES APP_AGEND_UT."USER" (USER_ID);

ALTER TABLE APP_AGEND_UT.SCHEDULE_EXTENSION ADD CONSTRAINT SCHEDULE_EXTENSION_WORK_SHIFT_ID_FK
FOREIGN KEY (WORK_SHIFT_ID)
REFERENCES APP_AGEND_UT.WORK_SHIFT (WORK_SHIFT_ID);

COMMIT;