ALTER TABLE "USER" ADD CONSTRAINT USER_IDENTIFICATION_TYPE_ID_FK
FOREIGN KEY (IDENTIFICATION_TYPE_ID)
REFERENCES IDENTIFICATION_TYPE (IDENTIFICATION_TYPE_ID);

ALTER TABLE "USER" ADD CONSTRAINT USER_ROLE_ID_FK
FOREIGN KEY (ROLE_ID)
REFERENCES "ROLE" (ROLE_ID);

ALTER TABLE WORK_SHIFT ADD CONSTRAINT WORK_SHIFT_SCHEDULE_ID_FK
FOREIGN KEY (SCHEDULE_ID)
REFERENCES SCHEDULE (SCHEDULE_ID);

ALTER TABLE WORK_SHIFT ADD CONSTRAINT WORK_SHIFT_USER_ID_FK
FOREIGN KEY (USER_ID)
REFERENCES "USER" (USER_ID);

ALTER TABLE SCHEDULE_EXTENSION ADD CONSTRAINT SCHEDULE_EXTENSION_WORK_SHIFT_ID_FK
FOREIGN KEY (WORK_SHIFT_ID)
REFERENCES WORK_SHIFT (WORK_SHIFT_ID);