CREATE TYPE WORK_SHIFT_REPORT_TYPE AS OBJECT (
    IDENTIFICATION_TYPE VARCHAR2(50),
    IDENTIFICATION_NUMBER VARCHAR2(50),
    FULL_NAME VARCHAR2(200),
    EMAIL VARCHAR2(100),
    ROLE VARCHAR2(50),
    SCHEDULE VARCHAR2(50),
    START_TIME VARCHAR2(50),
    END_TIME VARCHAR2(50),
    IS_STARTED VARCHAR2(50),
    EXTENSION_START_TIME VARCHAR2(50),
    EXTENSION_END_TIME VARCHAR2(50),
    EXTENSION_REASON VARCHAR2(500)
);

CREATE TYPE WORK_SHIFT_REPORT_LIST AS TABLE OF WORK_SHIFT_REPORT_TYPE;